export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ORIGIN: 'FORBIDDEN_ORIGIN',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  NOT_FOUND: 'NOT_FOUND',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  JIRA_NOT_CONNECTED: 'JIRA_NOT_CONNECTED',
  JIRA_REAUTH_REQUIRED: 'JIRA_REAUTH_REQUIRED',
  JIRA_FORBIDDEN: 'JIRA_FORBIDDEN',
  JIRA_RATE_LIMITED: 'JIRA_RATE_LIMITED',
  JIRA_UNAVAILABLE: 'JIRA_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ValidationDetail {
  field: string;
  constraints: string[];
}

/** Normalized error body returned by every endpoint. */
export interface ErrorBody {
  code: string;
  message: string;
  details?: ValidationDetail[];
}
