/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a local account
     * @description Only when LOCAL_REGISTRATION_ENABLED=true. Does not log in.
     */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in with email and password
     * @description Creates a server-side session and sets the jd.sid cookie.
     */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Destroy the current session and clear the cookie (idempotent) */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user and Jira connection status */
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get my preferences (defaults are created on first access) */
    get: operations['PreferencesController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update my preferences (only whitelisted fields) */
    patch: operations['PreferencesController_update'];
    trace?: never;
  };
  '/api/v1/jira/connection': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jira connection state (no network call, no secrets) */
    get: operations['JiraConnectionController_status'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jira/connection/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify the Jira credentials with a read-only call to /myself */
    post: operations['JiraConnectionController_verify'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jira/issues/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Jira issues by text or key (read-only, token-paginated) */
    get: operations['JiraIssuesController_search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/dashboard/issues/{issueKey}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Issue detail with subtasks and story points (read-only) */
    get: operations['DashboardIssuesController_getIssue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/tracked-issues': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My followed issues with progress; one failing issue never fails the list */
    get: operations['TrackingController_list'];
    put?: never;
    /** Follow an issue (verified readable in Jira first; idempotent) */
    post: operations['TrackingController_add'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/tracked-issues/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Stop following an issue (idempotent; only my own entries) */
    delete: operations['TrackingController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Application and database health (no configuration details) */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /**
       * Format: email
       * @description Trimmed and lowercased before storage
       * @example ana@example.com
       */
      email: string;
      /** Format: password */
      password: string;
      /** @example Ana */
      displayName?: string;
    };
    JiraStatusDto: {
      /**
       * @description Placeholder until Phase 2 (Jira OAuth)
       * @example false
       */
      connected: boolean;
    };
    MeResponseDto: {
      /** Format: uuid */
      userId: string;
      /** @example ana@example.com */
      email: string;
      /** @example Ana */
      displayName: string | null;
      jira: components['schemas']['JiraStatusDto'];
    };
    ValidationDetailDto: {
      /** @example password */
      field: string;
      /**
       * @example [
       *       "password must be longer than or equal to 12 characters"
       *     ]
       */
      constraints: string[];
    };
    ErrorResponseDto: {
      /**
       * @example UNAUTHENTICATED
       * @enum {string}
       */
      code:
        | 'UNAUTHENTICATED'
        | 'INVALID_CREDENTIALS'
        | 'VALIDATION_ERROR'
        | 'RATE_LIMITED'
        | 'FORBIDDEN'
        | 'FORBIDDEN_ORIGIN'
        | 'REGISTRATION_DISABLED'
        | 'EMAIL_ALREADY_REGISTERED'
        | 'NOT_FOUND'
        | 'DATABASE_UNAVAILABLE'
        | 'JIRA_NOT_CONNECTED'
        | 'JIRA_REAUTH_REQUIRED'
        | 'JIRA_FORBIDDEN'
        | 'ISSUE_NOT_FOUND_OR_INACCESSIBLE'
        | 'JIRA_RATE_LIMITED'
        | 'JIRA_UNAVAILABLE'
        | 'TRACKING_LIMIT_REACHED'
        | 'INTERNAL_ERROR';
      /** @example Authentication required */
      message: string;
      /** @description Present only for VALIDATION_ERROR */
      details?: components['schemas']['ValidationDetailDto'][];
    };
    LoginDto: {
      /** @example ana@example.com */
      email: string;
      /** Format: password */
      password: string;
    };
    PreferencesResponseDto: {
      /**
       * @example monday
       * @enum {string}
       */
      weekStartsOn: 'monday' | 'sunday';
      /** @example America/Argentina/Buenos_Aires */
      timezone: string | null;
      showWeeklySp: boolean;
      showSubtasks: boolean;
      showDependencies: boolean;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdatePreferencesDto: {
      /** @enum {string} */
      weekStartsOn?: 'monday' | 'sunday';
      /**
       * @description IANA time zone; null clears it
       * @example America/Argentina/Buenos_Aires
       */
      timezone?: string | null;
      showWeeklySp?: boolean;
      showSubtasks?: boolean;
      showDependencies?: boolean;
    };
    JiraConnectionStatusDto: {
      /**
       * @example api_token
       * @enum {string}
       */
      mode: 'api_token';
      /**
       * @example configured
       * @enum {string}
       */
      status: 'not_configured' | 'configured';
      /** @example https://acme.atlassian.net */
      siteUrl: string | null;
    };
    JiraConnectionVerifyDto: {
      /**
       * @example connected
       * @enum {string}
       */
      status: 'connected';
      /** @example https://acme.atlassian.net */
      siteUrl: string;
      /** @example Ada Lovelace */
      displayName: string;
      /**
       * Format: date-time
       * @description When Jira was queried.
       */
      checkedAt: string;
    };
    IssueTypeDto: {
      /**
       * @description Issue type id (names are localized).
       * @example 10001
       */
      id: string;
      /** @example Story */
      name: string;
      /** @example 0 */
      hierarchyLevel: number;
      isSubtask: boolean;
    };
    IssueStatusDto: {
      /** @example In progress */
      name: string;
      /** @enum {string} */
      categoryKey: 'new' | 'indeterminate' | 'done' | 'unknown';
      /** @description The configured cancelled status (done category, not completed). */
      isCancelled: boolean;
      /** @description Configured "available to take" status (D-025); never true for done or cancelled issues. */
      isAvailable: boolean;
    };
    IssueSummaryDto: {
      /** @example MASIN-123 */
      key: string;
      summary: string;
      issueType: components['schemas']['IssueTypeDto'];
      status: components['schemas']['IssueStatusDto'];
      /** @example https://acme.atlassian.net/browse/MASIN-123 */
      url: string;
    };
    IssueMetadataDto: {
      /**
       * Format: date-time
       * @description When Jira was queried.
       */
      fetchedAt: string;
      /**
       * @description Always false: data is read live from Jira.
       * @example false
       */
      isStale: boolean;
    };
    IssueSearchResponseDto: {
      items: components['schemas']['IssueSummaryDto'][];
      /** @description Opaque cursor for the next page; null on the last page. */
      nextPageToken: string | null;
      metadata: components['schemas']['IssueMetadataDto'];
    };
    StoryPointsDto: {
      /** @description Final SP; null means no estimate. */
      final: number | null;
      /** @description Planned SP; null means no estimate. */
      planned: number | null;
    };
    DashboardIssueDto: {
      id: string;
      /** @example MASIN-123 */
      key: string;
      summary: string;
      issueType: components['schemas']['IssueTypeDto'];
      status: components['schemas']['IssueStatusDto'];
      url: string;
      parentKey: string | null;
      storyPoints: components['schemas']['StoryPointsDto'];
    };
    DashboardSubtaskDto: {
      key: string;
      summary: string;
      status: components['schemas']['IssueStatusDto'];
      url: string;
    };
    ProgressDto: {
      /**
       * @description What was counted; none = nothing applies.
       * @enum {string}
       */
      basis: 'subtasks' | 'children' | 'none';
      /**
       * @description ok = percent available; none = no data (never 0%); all_cancelled = all cancelled.
       * @enum {string}
       */
      state: 'ok' | 'none' | 'all_cancelled';
      /** @description Denominator (cancelled excluded by default, D-024). */
      total: number;
      completed: number;
      inProgress: number;
      pending: number;
      /** @description Pending items available to take (D-025). A subset of pending, not an extra bucket. */
      available: number;
      /** @description Cancelled items, always reported separately. */
      cancelled: number;
      /** @description Items with an unrecognized status category (never completed). */
      unknown: number;
      /** @description 0-100, one decimal; null = no data. */
      percent: number | null;
      /** @description True when the children list was truncated at the hard cap. */
      isApproximate: boolean;
    };
    DashboardChildDto: {
      key: string;
      summary: string;
      issueType: components['schemas']['IssueTypeDto'];
      status: components['schemas']['IssueStatusDto'];
      url: string;
      storyPoints: components['schemas']['StoryPointsDto'];
      /** @description Progress of the child by its own subtasks. */
      progress: components['schemas']['ProgressDto'];
    };
    IssueDetailMetadataDto: {
      /**
       * Format: date-time
       * @description When Jira was queried.
       */
      fetchedAt: string;
      /**
       * @description Always false: data is read live from Jira.
       * @example false
       */
      isStale: boolean;
      warnings: string[];
    };
    DashboardIssueResponseDto: {
      issue: components['schemas']['DashboardIssueDto'];
      subtasks: components['schemas']['DashboardSubtaskDto'][];
      progress: components['schemas']['ProgressDto'];
      /** @description Direct children (epics only; absent otherwise). */
      children?: components['schemas']['DashboardChildDto'][];
      metadata: components['schemas']['IssueDetailMetadataDto'];
    };
    AddTrackedIssueDto: {
      /**
       * @description Jira issue key. Trimmed and uppercased before validation.
       * @example MASIN-123
       */
      issueKey: string;
    };
    TrackedIssueEntryDto: {
      /**
       * Format: uuid
       * @description Id of the tracking entry (not the Jira issue id).
       */
      id: string;
      /** @example MASIN-123 */
      issueKey: string;
      /** Format: date-time */
      addedAt: string;
    };
    TrackedIssueSummaryDto: {
      /** @example MASIN-123 */
      key: string;
      summary: string;
      issueType: components['schemas']['IssueTypeDto'];
      status: components['schemas']['IssueStatusDto'];
      url: string;
      storyPoints: components['schemas']['StoryPointsDto'];
    };
    TrackedIssueErrorDto: {
      /**
       * @description Normalized code (same set as the endpoint errors).
       * @example ISSUE_NOT_FOUND_OR_INACCESSIBLE
       */
      code: string;
      message: string;
    };
    TrackedIssueItemDto: {
      /**
       * Format: uuid
       * @description Id of the tracking entry (not the Jira issue id).
       */
      id: string;
      /** @example MASIN-123 */
      issueKey: string;
      /** Format: date-time */
      addedAt: string;
      /** @enum {string} */
      status: 'ok' | 'error';
      /** @description Only when status is ok. */
      issue?: components['schemas']['TrackedIssueSummaryDto'];
      /** @description Only when status is ok. Never present (not even zeros) for an errored item. */
      progress?: components['schemas']['ProgressDto'];
      /** @description Direct children count; epics with status ok only. */
      childrenCount?: number;
      /** @description Only when status is ok. */
      warnings?: string[];
      /**
       * Format: date-time
       * @description When Jira was read for this item. A cached item keeps its original read time; for an error it is the attempt time.
       */
      fetchedAt: string;
      /** @description Only when status is error. */
      error?: components['schemas']['TrackedIssueErrorDto'];
    };
    TrackedIssuesMetadataDto: {
      /**
       * Format: date-time
       * @description When this list was assembled.
       */
      fetchedAt: string;
    };
    TrackedIssuesResponseDto: {
      /** @description Ordered by display order. */
      items: components['schemas']['TrackedIssueItemDto'][];
      metadata: components['schemas']['TrackedIssuesMetadataDto'];
    };
    HealthResponseDto: {
      /** @enum {string} */
      status: 'ok';
      /** @enum {string} */
      database: 'up';
      /** Format: date-time */
      checkedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED, JIRA_NOT_CONNECTED (Jira credentials not configured) or TRACKING_LIMIT_REACHED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED (local throttle) or JIRA_RATE_LIMITED (Jira; see Retry-After) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED (local throttle) or JIRA_RATE_LIMITED (Jira; see Retry-After) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PreferencesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PreferencesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePreferencesDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  JiraConnectionController_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JiraConnectionStatusDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  JiraConnectionController_verify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JiraConnectionVerifyDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED, JIRA_NOT_CONNECTED (Jira credentials not configured) or TRACKING_LIMIT_REACHED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description JIRA_REAUTH_REQUIRED (Jira rejected the API token) or JIRA_FORBIDDEN (account lacks permission) */
      424: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED (local throttle) or JIRA_RATE_LIMITED (Jira; see Retry-After) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description DATABASE_UNAVAILABLE or JIRA_UNAVAILABLE */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  JiraIssuesController_search: {
    parameters: {
      query: {
        /** @description Free text or an issue key (e.g. MASIN-123). Trimmed, 2 to 100 characters. */
        q: string;
        /** @description Opaque cursor returned as nextPageToken by the previous page. */
        pageToken?: string;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssueSearchResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED, JIRA_NOT_CONNECTED (Jira credentials not configured) or TRACKING_LIMIT_REACHED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description JIRA_REAUTH_REQUIRED (Jira rejected the API token) or JIRA_FORBIDDEN (account lacks permission) */
      424: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED (local throttle) or JIRA_RATE_LIMITED (Jira; see Retry-After) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description DATABASE_UNAVAILABLE or JIRA_UNAVAILABLE */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  DashboardIssuesController_getIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        issueKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardIssueResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description ISSUE_NOT_FOUND_OR_INACCESSIBLE: the issue does not exist or is not visible (indistinguishable) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED, JIRA_NOT_CONNECTED (Jira credentials not configured) or TRACKING_LIMIT_REACHED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description JIRA_REAUTH_REQUIRED (Jira rejected the API token) or JIRA_FORBIDDEN (account lacks permission) */
      424: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED (local throttle) or JIRA_RATE_LIMITED (Jira; see Retry-After) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description DATABASE_UNAVAILABLE or JIRA_UNAVAILABLE */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  TrackingController_list: {
    parameters: {
      query?: {
        /** @description true skips the in-memory cache and reads Jira again. */
        refresh?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrackedIssuesResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  TrackingController_add: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddTrackedIssueDto'];
      };
    };
    responses: {
      /** @description Already tracked. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrackedIssueEntryDto'];
        };
      };
      /** @description Newly tracked. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrackedIssueEntryDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description ISSUE_NOT_FOUND_OR_INACCESSIBLE: the issue does not exist or is not visible (indistinguishable) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED, JIRA_NOT_CONNECTED (Jira credentials not configured) or TRACKING_LIMIT_REACHED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description JIRA_REAUTH_REQUIRED (Jira rejected the API token) or JIRA_FORBIDDEN (account lacks permission) */
      424: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED (local throttle) or JIRA_RATE_LIMITED (Jira; see Retry-After) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description DATABASE_UNAVAILABLE or JIRA_UNAVAILABLE */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  TrackingController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed, or nothing to remove. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      /** @description DATABASE_UNAVAILABLE or JIRA_UNAVAILABLE */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
}
