/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a local account
     * @description Only when LOCAL_REGISTRATION_ENABLED=true. Does not log in.
     */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in with email and password
     * @description Creates a server-side session and sets the jd.sid cookie.
     */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Destroy the current session and clear the cookie (idempotent) */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user and Jira connection status */
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get my preferences (defaults are created on first access) */
    get: operations['PreferencesController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update my preferences (only whitelisted fields) */
    patch: operations['PreferencesController_update'];
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Application and database health (no configuration details) */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /**
       * Format: email
       * @description Trimmed and lowercased before storage
       * @example ana@example.com
       */
      email: string;
      /** Format: password */
      password: string;
      /** @example Ana */
      displayName?: string;
    };
    JiraStatusDto: {
      /**
       * @description Placeholder until Phase 2 (Jira OAuth)
       * @example false
       */
      connected: boolean;
    };
    MeResponseDto: {
      /** Format: uuid */
      userId: string;
      /** @example ana@example.com */
      email: string;
      /** @example Ana */
      displayName: string | null;
      jira: components['schemas']['JiraStatusDto'];
    };
    ValidationDetailDto: {
      /** @example password */
      field: string;
      /**
       * @example [
       *       "password must be longer than or equal to 12 characters"
       *     ]
       */
      constraints: string[];
    };
    ErrorResponseDto: {
      /**
       * @example UNAUTHENTICATED
       * @enum {string}
       */
      code:
        | 'UNAUTHENTICATED'
        | 'INVALID_CREDENTIALS'
        | 'VALIDATION_ERROR'
        | 'RATE_LIMITED'
        | 'FORBIDDEN'
        | 'FORBIDDEN_ORIGIN'
        | 'REGISTRATION_DISABLED'
        | 'EMAIL_ALREADY_REGISTERED'
        | 'NOT_FOUND'
        | 'DATABASE_UNAVAILABLE'
        | 'INTERNAL_ERROR';
      /** @example Authentication required */
      message: string;
      /** @description Present only for VALIDATION_ERROR */
      details?: components['schemas']['ValidationDetailDto'][];
    };
    LoginDto: {
      /** @example ana@example.com */
      email: string;
      /** Format: password */
      password: string;
    };
    PreferencesResponseDto: {
      /**
       * @example monday
       * @enum {string}
       */
      weekStartsOn: 'monday' | 'sunday';
      /** @example America/Argentina/Buenos_Aires */
      timezone: string | null;
      showWeeklySp: boolean;
      showSubtasks: boolean;
      showDependencies: boolean;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdatePreferencesDto: {
      /** @enum {string} */
      weekStartsOn?: 'monday' | 'sunday';
      /**
       * @description IANA time zone; null clears it
       * @example America/Argentina/Buenos_Aires
       */
      timezone?: string | null;
      showWeeklySp?: boolean;
      showSubtasks?: boolean;
      showDependencies?: boolean;
    };
    HealthResponseDto: {
      /** @enum {string} */
      status: 'ok';
      /** @enum {string} */
      database: 'up';
      /** Format: date-time */
      checkedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description EMAIL_ALREADY_REGISTERED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description RATE_LIMITED */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PreferencesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  PreferencesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePreferencesDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description VALIDATION_ERROR: invalid or non-whitelisted input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description UNAUTHENTICATED (no valid session) or INVALID_CREDENTIALS (login) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      /** @description FORBIDDEN_ORIGIN (CSRF origin check) or REGISTRATION_DISABLED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      /** @description DATABASE_UNAVAILABLE */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
}
